### PR TITLE
Fixes #1150: Make docker multi arch builds possible for other platforms.

### LINKED ISSUE #1150: Dockerfile for arm64
Today I have tried to install the hornet node on my Raspberry PI 4 Model B by using the Ansible Playbook by nuriel77 [Playbook](https://github.com/nuriel77/hornet-playbook).

Unfortunately, the build for arch arm64 failed due to missing Dockerfile, the playbook is looking for the file named ./docker/Dockerfile.arm64, because the file ./docker/Dockerfile is tailored for amd64 only.

So it seems, that the current repository does not offer a Dockerfile for arm64 architecture.

The change was quite simple, please checkout my adopted file here:
https://github.com/whati001/hornet/blob/3887f6b499d86bad0f56da93b66fbd53e71df9e3/docker/Dockerfile.arm64

Changes I have done:
1) use a arm64 golang image -> golang:latest
https://github.com/whati001/hornet/blob/3887f6b499d86bad0f56da93b66fbd53e71df9e3/docker/Dockerfile.arm64#L6

2) use arm64 as GOARCH:
https://github.com/whati001/hornet/blob/3887f6b499d86bad0f56da93b66fbd53e71df9e3/docker/Dockerfile.arm64#L36

Is it still in scope to support arm64 (rapsi)?

### PR DESCRIPTION
**Pull request by legacycode**
# Description

This PR makes it possible to create multi arch docker files for docker hub. It also allows creating docker container on other platforms without changing the Dockerfile.

I created a multiarch hornet docker image and pushed it to dockerhub for testing purposes. You can find more informations at https://docs.docker.com/desktop/multi-arch/

Fixes #1150 

## Type of change

- [x] Enhancement (non-breaking change which adds functionality)

# How Has This Been Tested?

You can use following commands to generate a multi arch image on your preferred platform and push it to docker hub. Please change the docker tag.

```
docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker login -u *** -p ***
docker buildx build --platform linux/amd64,linux/arm64 -f docker/Dockerfile . -t legacycode/hornet --push
docker buildx imagetools inspect legacycode/hornet

Name:      docker.io/legacycode/hornet:latest
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:7f41d9f456caf8a2a73374c0fb18c0885d5c081995885325087867ad72205ec1

Manifests:
  Name:      docker.io/legacycode/hornet:latest@sha256:794f402333ba1edcb1b5eb56dddc109568ebc37f038d8055391f778c7554d36c
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      docker.io/legacycode/hornet:latest@sha256:a6df726e5cf4b4e11fadbc49fc8e741cfde7631963399391061eeccc46dba111
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64

```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have tested my code extensively
- [x] I have selected the `develop` branch as the target branch

### CODE REVIEW

**Comment by alexsporn** [comment]
Thanks for the PR. I'll have a look at it and adapt the release pipeline after the holidays.

**Comment by alexsporn** [comment]
Note for myself: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by legacycode** [comment]
Would be great to see this PR merged.

**Comment by muXxer** [comment]
Sorry @legacycode.
We just came back from vacation, and now other topics are high prio right now :(
We will have a look at this PR as soon as we have the time :+1:

**Review by alexsporn — APPROVED** [review]

**Comment by alexsporn** [comment]
Thanks for the PR. I'll try to adapt the build-pipeline for the next release to have multi-arch images deployed

**Pull request merged**
