### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by TeeVeeEss**
Fixed description layout

# Description

Please include a summary of the change. Include the motivation for the change.

Fixes lay-out error in wiki page

## Type of change

Please delete options that are not relevant.

- [x] Documentation Fix

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:
- [x] I have made corresponding changes to the documentation
- [x] I have selected the `develop` branch as the target branch

### CODE REVIEW

**Comment by Dr-Electron** [comment]
Actually @muXxer needs to fix that in his docs generator script. :wen: ? :trollface:

**Comment by TeeVeeEss** [comment]
Anything I can do? Otherwise I'll leave it up to you guys.

**Comment by muXxer** [comment]
I will have a look next week.
Thank you.

**Comment by muXxer** [comment]
Thank you very much @TeeVeeEss 
I fixed it now in all repos :+1:

**Pull request closed without merging**
