### PR TITLE
Reorganize With Diataxis

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description

Reorganised the docs following https://diataxis.fr

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Enhancement

# How Has This Been Tested?

Tested the local wiki build.
You can also just run https://gitpod.io/#https://github.com/Dr-Electron/hornet/tree/docs/feat/reorg

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have tested my code extensively
- [ ] I have selected the `develop` branch as the target branch

### CODE REVIEW

**Comment by Dr-Electron** [comment]
@iotaledger/tech-writers ready for your review

**Review by lucas-tortora — CHANGES_REQUESTED** [review]
Structure-wise it looks great :) , but we'd need to update the links in the files which were renamed without changes.  I'd add them as suggestion, but as they have no changes I can't suggest

**Comment by Dr-Electron** [comment]
> Structure-wise it looks great :) , but we'd need to update the links in the files which were renamed without changes. I'd add them as suggestion, but as they have no changes I can't suggest

There are broken links? Shouldn't they then break the test? 😅

**Comment by lucas-tortora** [comment]
> > Structure-wise it looks great :) , but we'd need to update the links in the files which were renamed without changes. I'd add them as suggestion, but as they have no changes I can't suggest
> 
> There are broken links? Shouldn't they then break the test? sweat_smile

according to my local build:

```


Error: Docs markdown link couldn't be resolved: (hornet_apt_repository.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/getting_started/getting_started.md for version current
    at Array.forEach (<anonymous>)
Error: Docs markdown link couldn't be resolved: (../post_installation/post_installation.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/how_tos/hornet_apt_repository.md for version current
    at Array.forEach (<anonymous>)
Error: Docs markdown link couldn't be resolved: (faq.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/troubleshooting.md for version current
```

**Comment by Dr-Electron** [comment]
> > > Structure-wise it looks great :) , but we'd need to update the links in the files which were renamed without changes. I'd add them as suggestion, but as they have no changes I can't suggest
> > 
> > 
> > There are broken links? Shouldn't they then break the test? sweat_smile
> 
> according to my local build:
> 
> ```
> 
> 
> Error: Docs markdown link couldn't be resolved: (hornet_apt_repository.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/getting_started/getting_started.md for version current
>     at Array.forEach (<anonymous>)
> Error: Docs markdown link couldn't be resolved: (../post_installation/post_installation.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/how_tos/hornet_apt_repository.md for version current
>     at Array.forEach (<anonymous>)
> Error: Docs markdown link couldn't be resolved: (faq.md) in /home/lucas/Documents/IOTA/coworkers/drelectron/hornet/documentation/docs/troubleshooting.md for version current
> ```

Damn, good catch. I think I know what's wrong. Let me fix it

**Review by aleksei-korolev — COMMENTED** [review]
Do you use the same version of docs template as @lucas-tortora ? He has more files in his PR.

**Comment by Dr-Electron** [comment]
> Do you use the same version of docs template as @lucas-tortora ? He has more files in his PR.

What do you mean with he has more files? Isn't that dependent on the docs how many files there are?

**Comment by aleksei-korolev** [comment]
I was talking about files like `documentation/docs/getting_started/_README.md` in https://github.com/iotaledger/stronghold.rs/pull/377/files

Do we want to keep them or omit them?

**Comment by lucas-tortora** [comment]
> I was talking about files like `documentation/docs/getting_started/_README.md` in https://github.com/iotaledger/stronghold.rs/pull/377/files
> 
> Do we want to keep them or omit them?

Perhaps it's better to omit them, though they won't change often if we just keep an intro in the main readme and a link to the repo it'll be much less maintenance.

**Comment by Dr-Electron** [comment]
> > I was talking about files like `documentation/docs/getting_started/_README.md` in https://github.com/iotaledger/stronghold.rs/pull/377/files
> > Do we want to keep them or omit them?
> 
> Perhaps it's better to omit them, though they won't change often if we just keep an intro in the main readme and a link to the repo it'll be much less maintenance.

As it seems we agree on that let's not add the _md files and one everything into the wiki guide. And add the https://wiki.iota.org/participate/contribute-to-wiki/for_devs/developer_guide link to the docs README

**Review by lucas-tortora — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Pull request merged**
